import sanitizeHtml from "sanitize-html";

export function sanitizeCmsHtml(input: unknown) {
  const html = typeof input === "string" ? input : "";

  return sanitizeHtml(html, {
    allowedTags: [
      "html",
      "head",
      "body",
      "main",
      "header",
      "footer",
      "section",
      "article",
      "aside",
      "nav",
      "div",
      "span",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "p",
      "br",
      "hr",
      "strong",
      "b",
      "em",
      "i",
      "u",
      "s",
      "small",
      "mark",
      "blockquote",
      "code",
      "pre",
      "ul",
      "ol",
      "li",
      "a",
      "figure",
      "figcaption",
      "picture",
      "source",
      "img",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "colgroup",
      "col",
      "iframe",
      "video",
      "audio"
    ],
    allowedAttributes: {
      "*": ["id", "class", "style", "role", "data-*", "aria-*"],
      a: ["href", "name", "target", "rel"],
      img: [
        "src",
        "alt",
        "title",
        "loading",
        "decoding",
        "width",
        "height",
        "data-width",
        "data-width-px",
        "data-in-table",
        "data-align"
      ],
      source: ["src", "srcset", "type", "media", "sizes"],
      iframe: [
        "src",
        "title",
        "loading",
        "allow",
        "allowfullscreen",
        "frameborder",
        "referrerpolicy",
        "width",
        "height"
      ],
      video: [
        "src",
        "controls",
        "autoplay",
        "muted",
        "loop",
        "playsinline",
        "poster",
        "preload",
        "width",
        "height"
      ],
      audio: ["src", "controls", "autoplay", "muted", "loop", "preload"],
      table: ["data-align"],
      th: [
        "colspan",
        "rowspan",
        "scope",
        "data-bg",
        "data-colwidth",
        "data-height-px",
        "data-border",
        "data-border-color",
        "data-border-width",
        "data-align"
      ],
      td: [
        "colspan",
        "rowspan",
        "data-bg",
        "data-colwidth",
        "data-height-px",
        "data-border",
        "data-border-color",
        "data-border-width",
        "data-align"
      ],
      col: ["span"]
    },
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowedSchemesByTag: {
      img: ["http", "https", "data"],
      source: ["http", "https", "data"],
      iframe: ["http", "https"],
      video: ["http", "https"],
      audio: ["http", "https"]
    },
    allowProtocolRelative: false,
    allowedStyles: {
      "*": {
        color: [
          /^#[0-9a-fA-F]{3,8}$/,
          /^rgb\(/,
          /^rgba\(/,
          /^hsl\(/,
          /^hsla\(/
        ],
        "background-color": [
          /^#[0-9a-fA-F]{3,8}$/,
          /^rgb\(/,
          /^rgba\(/,
          /^hsl\(/,
          /^hsla\(/
        ],
        "background-image": [/^none$/, /^url\(["']?https?:\/\//i],
        "text-align": [/^(left|center|right|justify)$/],
        "font-size": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        "font-weight": [/^(normal|bold|[1-9]00)$/],
        "font-style": [/^(normal|italic|oblique)$/],
        "line-height": [/^\d+(\.\d+)?(px|rem|em|%)?$/],
        "letter-spacing": [/^-?\d+(\.\d+)?(px|rem|em)$/],
        "text-decoration": [/^[a-z\s-]+$/i],
        "text-transform": [/^(none|uppercase|lowercase|capitalize)$/],
        display: [/^(block|inline|inline-block|flex|grid|none)$/],
        width: [/^\d+(\.\d+)?(px|rem|em|%|vw)$/],
        height: [/^\d+(\.\d+)?(px|rem|em|%|vh)$/],
        "max-width": [/^\d+(\.\d+)?(px|rem|em|%|vw)$/],
        "max-height": [/^\d+(\.\d+)?(px|rem|em|%|vh)$/],
        "min-width": [/^\d+(\.\d+)?(px|rem|em|%|vw)$/],
        "min-height": [/^\d+(\.\d+)?(px|rem|em|%|vh)$/],
        margin: [
          /^-?\d+(\.\d+)?(px|rem|em|%)?(\s+-?\d+(\.\d+)?(px|rem|em|%)?){0,3}$/,
          /^auto$/
        ],
        "margin-top": [/^-?\d+(\.\d+)?(px|rem|em|%)$/, /^auto$/],
        "margin-right": [/^-?\d+(\.\d+)?(px|rem|em|%)$/, /^auto$/],
        "margin-bottom": [/^-?\d+(\.\d+)?(px|rem|em|%)$/, /^auto$/],
        "margin-left": [/^-?\d+(\.\d+)?(px|rem|em|%)$/, /^auto$/],
        padding: [
          /^\d+(\.\d+)?(px|rem|em|%)?(\s+\d+(\.\d+)?(px|rem|em|%)?){0,3}$/
        ],
        "padding-top": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        "padding-right": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        "padding-bottom": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        "padding-left": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        border: [/^[\w\s().,#%-]+$/],
        "border-color": [
          /^#[0-9a-fA-F]{3,8}$/,
          /^rgb\(/,
          /^rgba\(/,
          /^hsl\(/,
          /^hsla\(/
        ],
        "border-width": [/^\d+(\.\d+)?px$/],
        "border-style": [/^(none|solid|dashed|dotted|double)$/],
        "border-radius": [/^\d+(\.\d+)?(px|rem|em|%)$/],
        "object-fit": [/^(fill|contain|cover|none|scale-down)$/],
        "object-position": [/^[\w\s%.-]+$/],
        "white-space": [/^(normal|nowrap|pre|pre-line|pre-wrap|break-spaces)$/],
        "word-break": [/^(normal|break-word|break-all|keep-all)$/],
        "overflow-x": [/^(auto|hidden|scroll|visible)$/],
        "overflow-y": [/^(auto|hidden|scroll|visible)$/]
      }
    }
  });
}
